begin;
drop function if exists public.link_transaction_property(uuid,uuid,uuid,uuid,text,text,timestamptz);
drop function if exists public.archive_property_interest(uuid,uuid,uuid,integer,text,text,timestamptz);
drop function if exists public.link_property_interest(uuid,uuid,uuid,uuid,text,text,text,timestamptz,text,timestamptz);
drop function if exists public.upsert_property_fact(uuid,uuid,uuid,text,jsonb,text,text,text,text,timestamptz,text,timestamptz,timestamptz,integer,text,timestamptz);
drop function if exists public.update_property_identity(uuid,uuid,uuid,integer,text,text,text,text,text,text,text,text,text,timestamptz);
drop function if exists public.create_manual_property(uuid,uuid,text,text,text,text,text,text,text,text,timestamptz);
drop function if exists public.normalized_property_address(text,text,text,text,text);
drop trigger if exists property_interest_events_no_mutation on public.property_interest_events;
drop trigger if exists property_fact_revisions_no_mutation on public.property_fact_revisions;
drop trigger if exists property_identity_revisions_no_mutation on public.property_identity_revisions;
drop function if exists public.reject_property_history_mutation();
drop table if exists public.transaction_property_links;
drop table if exists public.property_interest_events;
drop table if exists public.property_interests;
drop table if exists public.property_fact_revisions;
drop table if exists public.property_facts;
drop table if exists public.property_identity_revisions;
drop table if exists public.properties;
commit;
