-- Story 9.4: append-only property behavior and governed CMA research.
create table public.property_behavior_events (
  id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete restrict,property_id uuid not null,contact_id uuid not null,
  behavior_type text not null,source text not null,source_reference text not null,source_occurred_at timestamptz not null,permission_state text not null,
  idempotency_key text not null,recorded_by_membership_id uuid not null,created_at timestamptz not null,
  constraint property_behavior_events_workspace_unique unique(id,workspace_id),constraint property_behavior_events_replay_unique unique(workspace_id,idempotency_key),
  constraint property_behavior_events_property_fk foreign key(property_id,workspace_id) references public.properties(id,workspace_id) on delete restrict,
  constraint property_behavior_events_contact_fk foreign key(contact_id,workspace_id) references public.contacts(id,workspace_id) on delete restrict,
  constraint property_behavior_events_actor_fk foreign key(recorded_by_membership_id,workspace_id) references public.workspace_members(id,workspace_id) on delete restrict,
  constraint property_behavior_events_values check(behavior_type in ('inquiry','view','saved','favorite','showing-request','seller-intake') and source in ('website','manual','licensed-provider') and length(source_reference) between 1 and 240 and permission_state in ('allowed','restricted','revoked') and idempotency_key~'^[A-Za-z0-9._:-]{8,160}$')
);
create table public.cma_requests (
  id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete restrict,property_id uuid not null,contact_id uuid,
  purpose text not null,selection_criteria jsonb not null,as_of timestamptz not null,provider_authority_id uuid,state text not null,blocked_reason text,current_version integer not null default 1,
  idempotency_key text not null,created_by_membership_id uuid not null,updated_by_membership_id uuid not null,created_at timestamptz not null,updated_at timestamptz not null,
  constraint cma_requests_workspace_unique unique(id,workspace_id),constraint cma_requests_replay_unique unique(workspace_id,idempotency_key),
  constraint cma_requests_property_fk foreign key(property_id,workspace_id) references public.properties(id,workspace_id) on delete restrict,
  constraint cma_requests_contact_fk foreign key(contact_id,workspace_id) references public.contacts(id,workspace_id) on delete restrict,
  constraint cma_requests_authority_fk foreign key(provider_authority_id,workspace_id) references public.listing_provider_authorities(id,workspace_id) on delete restrict,
  constraint cma_requests_creator_fk foreign key(created_by_membership_id,workspace_id) references public.workspace_members(id,workspace_id) on delete restrict,
  constraint cma_requests_updater_fk foreign key(updated_by_membership_id,workspace_id) references public.workspace_members(id,workspace_id) on delete restrict,
  constraint cma_requests_values check(purpose in ('seller-consultation','buyer-offer','listing-review') and jsonb_typeof(selection_criteria)='object' and state in ('blocked','draft','researching','ready-for-review','completed','expired','cancelled') and current_version>0 and idempotency_key~'^[A-Za-z0-9._:-]{8,160}$' and ((state='blocked' and blocked_reason is not null) or state<>'blocked'))
);
create table public.cma_comparable_candidates (
  id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete restrict,cma_request_id uuid not null,licensed_record_id uuid not null,
  provider_record_id text not null,source_reference text not null,provider_modified_at timestamptz not null,distance_miles numeric(8,3) not null,included boolean not null,decision_reason text not null,created_at timestamptz not null,
  constraint cma_comparable_candidates_workspace_unique unique(id,workspace_id),constraint cma_comparable_candidates_once unique(cma_request_id,licensed_record_id),
  constraint cma_comparable_candidates_request_fk foreign key(cma_request_id,workspace_id) references public.cma_requests(id,workspace_id) on delete restrict,
  constraint cma_comparable_candidates_record_fk foreign key(licensed_record_id,workspace_id) references public.licensed_listing_records(id,workspace_id) on delete restrict,
  constraint cma_comparable_candidates_values check(length(provider_record_id) between 1 and 160 and length(source_reference) between 1 and 240 and distance_miles between 0 and 100 and length(decision_reason) between 1 and 240)
);
create index property_behavior_contact_time_idx on public.property_behavior_events(workspace_id,contact_id,source_occurred_at desc);
create index cma_requests_workspace_state_idx on public.cma_requests(workspace_id,state,updated_at desc);

create or replace function public.guard_property_behavior_history() returns trigger language plpgsql set search_path='' as $$begin raise exception 'property behavior and comparable evidence is append-only' using errcode='55000';end$$;
create trigger property_behavior_events_guard before update or delete on public.property_behavior_events for each row execute function public.guard_property_behavior_history();
create trigger cma_comparable_candidates_guard before update or delete on public.cma_comparable_candidates for each row execute function public.guard_property_behavior_history();

create or replace function public.record_property_behavior(target_workspace_id uuid,target_membership_id uuid,target_property_id uuid,target_contact_id uuid,target_behavior_type text,target_source text,target_source_reference text,target_source_occurred_at timestamptz,target_permission_state text,target_idempotency_key text,target_occurred_at timestamptz)
returns jsonb language plpgsql security definer set search_path='' as $$declare saved public.property_behavior_events%rowtype;begin
 perform public.assert_crm_actor_membership(target_membership_id,target_workspace_id);
 perform 1 from public.properties where id=target_property_id and workspace_id=target_workspace_id;if not found then raise exception 'property unavailable' using errcode='P0002';end if;
 perform 1 from public.contacts where id=target_contact_id and workspace_id=target_workspace_id;if not found then raise exception 'contact unavailable' using errcode='P0002';end if;
 if target_behavior_type not in ('inquiry','view','saved','favorite','showing-request','seller-intake') or target_source not in ('website','manual','licensed-provider') or target_permission_state not in ('allowed','restricted','revoked') or length(trim(target_source_reference)) not between 1 and 240 or target_idempotency_key!~'^[A-Za-z0-9._:-]{8,160}$' then raise exception 'invalid property behavior' using errcode='22023';end if;
 insert into public.property_behavior_events(workspace_id,property_id,contact_id,behavior_type,source,source_reference,source_occurred_at,permission_state,idempotency_key,recorded_by_membership_id,created_at) values(target_workspace_id,target_property_id,target_contact_id,target_behavior_type,target_source,trim(target_source_reference),target_source_occurred_at,target_permission_state,target_idempotency_key,target_membership_id,target_occurred_at) on conflict(workspace_id,idempotency_key) do nothing returning * into saved;
 if not found then select * into saved from public.property_behavior_events where workspace_id=target_workspace_id and idempotency_key=target_idempotency_key;return jsonb_build_object('eventId',saved.id,'noOp',true);end if;return jsonb_build_object('eventId',saved.id,'noOp',false);
end$$;

create or replace function public.create_cma_request(target_workspace_id uuid,target_membership_id uuid,target_property_id uuid,target_contact_id uuid,target_purpose text,target_selection_criteria jsonb,target_as_of timestamptz,target_provider_authority_id uuid,target_idempotency_key text,target_occurred_at timestamptz)
returns jsonb language plpgsql security definer set search_path='' as $$declare authority public.listing_provider_authorities%rowtype;saved public.cma_requests%rowtype;initial_state text;reason text;begin
 perform public.assert_crm_actor_membership(target_membership_id,target_workspace_id);perform 1 from public.properties where id=target_property_id and workspace_id=target_workspace_id;if not found then raise exception 'property unavailable' using errcode='P0002';end if;if target_contact_id is not null then perform 1 from public.contacts where id=target_contact_id and workspace_id=target_workspace_id;if not found then raise exception 'contact unavailable' using errcode='P0002';end if;end if;
 if target_purpose not in ('seller-consultation','buyer-offer','listing-review') or jsonb_typeof(target_selection_criteria)<>'object' or target_idempotency_key!~'^[A-Za-z0-9._:-]{8,160}$' then raise exception 'invalid CMA request' using errcode='22023';end if;
 if target_provider_authority_id is not null then select * into authority from public.listing_provider_authorities where id=target_provider_authority_id and workspace_id=target_workspace_id;end if;
 if authority.id is null or authority.state<>'active' or target_as_of<authority.effective_at or (authority.expires_at is not null and target_as_of>=authority.expires_at) then initial_state:='blocked';reason:='Licensed comparable access is unavailable or expired.';else initial_state:='draft';reason:=null;end if;
 insert into public.cma_requests(workspace_id,property_id,contact_id,purpose,selection_criteria,as_of,provider_authority_id,state,blocked_reason,idempotency_key,created_by_membership_id,updated_by_membership_id,created_at,updated_at) values(target_workspace_id,target_property_id,target_contact_id,target_purpose,target_selection_criteria,target_as_of,target_provider_authority_id,initial_state,reason,target_idempotency_key,target_membership_id,target_membership_id,target_occurred_at,target_occurred_at) on conflict(workspace_id,idempotency_key) do nothing returning * into saved;
 if not found then select * into saved from public.cma_requests where workspace_id=target_workspace_id and idempotency_key=target_idempotency_key;return jsonb_build_object('requestId',saved.id,'state',saved.state,'blockedReason',saved.blocked_reason,'noOp',true);end if;return jsonb_build_object('requestId',saved.id,'state',saved.state,'blockedReason',saved.blocked_reason,'noOp',false);
end$$;

create or replace function public.add_cma_comparable_candidate(target_workspace_id uuid,target_cma_request_id uuid,target_licensed_record_id uuid,target_distance_miles numeric,target_included boolean,target_decision_reason text,target_occurred_at timestamptz)
returns jsonb language plpgsql security definer set search_path='' as $$declare request public.cma_requests%rowtype;record public.licensed_listing_records%rowtype;authority public.listing_provider_authorities%rowtype;saved public.cma_comparable_candidates%rowtype;begin
 if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501';end if;select * into request from public.cma_requests where id=target_cma_request_id and workspace_id=target_workspace_id and state in ('draft','researching');if not found then raise exception 'CMA request is not researchable' using errcode='55000';end if;select * into record from public.licensed_listing_records where id=target_licensed_record_id and workspace_id=target_workspace_id and permission_state='allowed' and display_until>=target_occurred_at and deleted_at is null;if not found then raise exception 'licensed comparable is unavailable' using errcode='55000';end if;select * into authority from public.listing_provider_authorities where id=record.authority_id and id=request.provider_authority_id and workspace_id=target_workspace_id and state='active';if not found then raise exception 'licensed comparable authority is unavailable' using errcode='55000';end if;if target_distance_miles<0 or target_distance_miles>100 or length(trim(target_decision_reason)) not between 1 and 240 then raise exception 'invalid comparable decision' using errcode='22023';end if;
 insert into public.cma_comparable_candidates(workspace_id,cma_request_id,licensed_record_id,provider_record_id,source_reference,provider_modified_at,distance_miles,included,decision_reason,created_at) values(target_workspace_id,request.id,record.id,record.provider_record_id,authority.attribution_url,record.provider_modified_at,target_distance_miles,target_included,trim(target_decision_reason),target_occurred_at) on conflict(cma_request_id,licensed_record_id) do nothing returning * into saved;if not found then select * into saved from public.cma_comparable_candidates where cma_request_id=request.id and licensed_record_id=record.id;return jsonb_build_object('candidateId',saved.id,'noOp',true);end if;update public.cma_requests set state='researching',current_version=current_version+1,updated_at=target_occurred_at where id=request.id and state='draft';return jsonb_build_object('candidateId',saved.id,'noOp',false);
end$$;

create or replace function public.transition_cma_request(target_workspace_id uuid,target_membership_id uuid,target_request_id uuid,target_expected_version integer,target_state text,target_reason text,target_occurred_at timestamptz)
returns jsonb language plpgsql security definer set search_path='' as $$declare saved public.cma_requests%rowtype;candidate_count integer;begin
 perform public.assert_crm_actor_membership(target_membership_id,target_workspace_id);if target_state not in ('ready-for-review','completed','expired','cancelled') or length(trim(target_reason)) not between 1 and 240 then raise exception 'invalid CMA transition' using errcode='22023';end if;select count(*) into candidate_count from public.cma_comparable_candidates where workspace_id=target_workspace_id and cma_request_id=target_request_id and included;if target_state in ('ready-for-review','completed') and candidate_count=0 then raise exception 'CMA requires at least one cited included comparable' using errcode='55000';end if;
 update public.cma_requests set state=target_state,blocked_reason=null,current_version=current_version+1,updated_by_membership_id=target_membership_id,updated_at=target_occurred_at where id=target_request_id and workspace_id=target_workspace_id and current_version=target_expected_version and state in ('draft','researching','ready-for-review') returning * into saved;if not found then raise exception 'CMA request changed; refresh and try again' using errcode='40001';end if;return jsonb_build_object('requestId',saved.id,'state',saved.state,'version',saved.current_version);
end$$;

alter table public.property_behavior_events enable row level security;alter table public.property_behavior_events force row level security;alter table public.cma_requests enable row level security;alter table public.cma_requests force row level security;alter table public.cma_comparable_candidates enable row level security;alter table public.cma_comparable_candidates force row level security;
create policy property_behavior_events_member_select on public.property_behavior_events for select to authenticated using(public.has_workspace_access(workspace_id));create policy cma_requests_member_select on public.cma_requests for select to authenticated using(public.has_workspace_access(workspace_id));create policy cma_comparable_candidates_member_select on public.cma_comparable_candidates for select to authenticated using(public.has_workspace_access(workspace_id));
revoke all on public.property_behavior_events,public.cma_requests,public.cma_comparable_candidates from public,anon,authenticated,service_role;grant select on public.property_behavior_events,public.cma_requests,public.cma_comparable_candidates to authenticated,service_role;
revoke all on function public.record_property_behavior(uuid,uuid,uuid,uuid,text,text,text,timestamptz,text,text,timestamptz),public.create_cma_request(uuid,uuid,uuid,uuid,text,jsonb,timestamptz,uuid,text,timestamptz),public.add_cma_comparable_candidate(uuid,uuid,uuid,numeric,boolean,text,timestamptz),public.transition_cma_request(uuid,uuid,uuid,integer,text,text,timestamptz) from public,anon,authenticated,service_role;
grant execute on function public.record_property_behavior(uuid,uuid,uuid,uuid,text,text,text,timestamptz,text,text,timestamptz),public.create_cma_request(uuid,uuid,uuid,uuid,text,jsonb,timestamptz,uuid,text,timestamptz),public.transition_cma_request(uuid,uuid,uuid,integer,text,text,timestamptz) to authenticated;grant execute on function public.add_cma_comparable_candidate(uuid,uuid,uuid,numeric,boolean,text,timestamptz) to service_role;revoke all on function public.guard_property_behavior_history() from public;
comment on table public.cma_requests is 'Governed comparable research request; it is not an appraisal or automated valuation.';
