export const PROPERTY_BEHAVIOR_TYPES = ['inquiry','view','saved','favorite','showing-request','seller-intake'] as const;
export type PropertyBehaviorType = (typeof PROPERTY_BEHAVIOR_TYPES)[number];
export const CMA_STATES = ['blocked','draft','researching','ready-for-review','completed','expired','cancelled'] as const;
export type CmaState = (typeof CMA_STATES)[number];

export interface RecordPropertyBehaviorInput { readonly propertyId:string;readonly contactId:string;readonly type:PropertyBehaviorType;readonly source:'website'|'manual'|'licensed-provider';readonly sourceReference:string;readonly occurredAt:string;readonly permissionState:'allowed'|'restricted'|'revoked';readonly idempotencyKey:string }
export interface CmaCriteria { readonly radiusMiles:number;readonly lookbackDays:number;readonly propertyKinds:readonly string[];readonly bedroomsTolerance:number;readonly bathroomsTolerance:number;readonly squareFeetTolerancePercent:number }
export interface CreateCmaRequestInput { readonly propertyId:string;readonly contactId?:string;readonly purpose:'seller-consultation'|'buyer-offer'|'listing-review';readonly criteria:CmaCriteria;readonly asOf:string;readonly providerAuthorityId?:string;readonly idempotencyKey:string }
export interface ComparableCandidate { readonly providerRecordId:string;readonly sourceReference:string;readonly providerModifiedAt:string;readonly distanceMiles:number;readonly included:boolean;readonly decisionReason:string }

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
const KEY=/^[A-Za-z0-9._:-]{8,160}$/u;
const text=(value:unknown,label:string,max:number)=>{if(typeof value!=='string')throw new Error(`${label} is required.`);const normalized=value.trim().replace(/\s+/gu,' ');if(!normalized||normalized.length>max||/[\p{Cc}\p{Cf}]/u.test(normalized))throw new Error(`${label} is invalid.`);return normalized;};
const instant=(value:unknown,label:string)=>{const normalized=text(value,label,64),date=new Date(normalized);if(!Number.isFinite(date.getTime()))throw new Error(`${label} is invalid.`);return date.toISOString();};
const number=(value:unknown,min:number,max:number,label:string,integer=false)=>{if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max||(integer&&!Number.isInteger(value)))throw new Error(`${label} is invalid.`);return value;};

export function validatePropertyBehavior(input:RecordPropertyBehaviorInput):RecordPropertyBehaviorInput {if(!UUID.test(input.propertyId)||!UUID.test(input.contactId))throw new Error('Choose a valid property and contact.');if(!PROPERTY_BEHAVIOR_TYPES.includes(input.type))throw new Error('Property behavior is invalid.');if(!['website','manual','licensed-provider'].includes(input.source))throw new Error('Behavior source is invalid.');if(!['allowed','restricted','revoked'].includes(input.permissionState))throw new Error('Behavior permission is invalid.');if(!KEY.test(input.idempotencyKey))throw new Error('Behavior idempotency key is invalid.');return Object.freeze({...input,sourceReference:text(input.sourceReference,'Behavior source',240),occurredAt:instant(input.occurredAt,'Behavior time')});}

export function validateCmaCriteria(input:CmaCriteria):CmaCriteria {const propertyKinds=[...new Set(input.propertyKinds.map((item)=>text(item,'Property type',40)))];if(!propertyKinds.length||propertyKinds.length>8)throw new Error('Choose between 1 and 8 property types.');return Object.freeze({radiusMiles:number(input.radiusMiles,0.1,100,'Comparable radius'),lookbackDays:number(input.lookbackDays,1,1825,'Comparable lookback',true),propertyKinds,bedroomsTolerance:number(input.bedroomsTolerance,0,10,'Bedroom tolerance',true),bathroomsTolerance:number(input.bathroomsTolerance,0,10,'Bathroom tolerance'),squareFeetTolerancePercent:number(input.squareFeetTolerancePercent,0,100,'Square-foot tolerance')});}

export function validateCreateCmaRequest(input:CreateCmaRequestInput):CreateCmaRequestInput {if(!UUID.test(input.propertyId)||input.contactId&&!UUID.test(input.contactId)||input.providerAuthorityId&&!UUID.test(input.providerAuthorityId))throw new Error('CMA relationships are invalid.');if(!['seller-consultation','buyer-offer','listing-review'].includes(input.purpose))throw new Error('CMA purpose is invalid.');if(!KEY.test(input.idempotencyKey))throw new Error('CMA idempotency key is invalid.');return Object.freeze({...input,criteria:validateCmaCriteria(input.criteria),asOf:instant(input.asOf,'CMA as-of time')});}

export function behaviorRecommendation(events:readonly {type:PropertyBehaviorType;occurredAt:string}[],now=new Date()):{eligible:boolean;reason:string;eventCount:number}{const recent=events.filter((event)=>now.getTime()-Date.parse(event.occurredAt)<=7*86400000);const showing=recent.some((event)=>event.type==='showing-request');const repeatViews=recent.filter((event)=>event.type==='view').length;return showing?{eligible:true,reason:'A showing was requested in the last 7 days.',eventCount:recent.length}:repeatViews>=3?{eligible:true,reason:`${repeatViews} verified property views occurred in the last 7 days.`,eventCount:recent.length}:{eligible:false,reason:'No showing request or verified repeat-view threshold is present.',eventCount:recent.length};}

export function cmaInitialState(provider:{state:string;expiresAt?:string},asOf:string):{state:'draft'|'blocked';reason:string}{if(provider.state!=='active')return{state:'blocked',reason:'Licensed comparable access is not active.'};if(provider.expiresAt&&Date.parse(provider.expiresAt)<=Date.parse(asOf))return{state:'blocked',reason:'Licensed comparable access has expired.'};return{state:'draft',reason:'Provider authority is active; comparable research still requires cited records.'};}
