import { readFile, writeFile } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { createContactTemplate, parsePortableContactImport } from '../lib/application/workbook-portability.ts';
import { createGovernedContactExport } from '../lib/application/governed-export.ts';
import { createOperationalApiPlaintext, operationalApiVerifier, OPERATIONAL_API_SCOPES, type OperationalApiScope } from '../lib/security/operational-api.ts';
import { createWebhookCredential, webhookSecretVerifier } from '../lib/security/generic-webhook.ts';
import { createAuthenticatedCliContext } from '../lib/data/authenticated-cli-context.ts';
import { supabaseRepository } from '../lib/data/supabase-repository.ts';
import { memoryRepository } from '../lib/data/memory-repository.ts';

const args = process.argv.slice(2); const command = args[0];
const value = (name: string) => { const index = args.indexOf(name); return index >= 0 ? args[index + 1] : undefined; };
const output = (payload: unknown) => process.stdout.write(`${JSON.stringify(payload, null, 2)}\n`);

if (command === 'template') {
  const format = value('--format') === 'xlsx' ? 'xlsx' : 'csv'; const target = resolve(value('--output') ?? `omnix-contacts-template.${format}`);
  const bytes = await createContactTemplate(format); await writeFile(target, bytes);
  output({ ok: true, schemaVersion: 'data-portability.v1', command, format, output: target, bytes: bytes.byteLength });
} else if (command === 'preview') {
  const file = args[1]; if (!file) throw new Error('Usage: npm run data -- preview <file.csv|file.vcf|file.xls|file.xlsx>');
  const bytes = new Uint8Array(await readFile(resolve(file))); const parsed = await parsePortableContactImport({ bytes, filename: basename(file) });
  output({ ok: true, schemaVersion: 'data-portability.v1', command, fileHash: createHash('sha256').update(bytes).digest('hex'), format: parsed.format, rows: parsed.totalRows, accepted: parsed.candidates.length, rejected: parsed.rejected.length, recognizedFields: parsed.recognizedFields, preservedFields: parsed.preservedFields, unknownFields: parsed.unknownFields });
} else if (command === 'export') {
  const format=value('--format')==='xlsx'?'xlsx':'csv'; const target=resolve(value('--output')??`omnix-contacts-export.${format}`); const fields=(value('--fields')??'id,firstName,lastName,email,phone,leadType,relationship,pipelineStage,nextTouchAt,updatedAt').split(',');
  const live=args.includes('--live'); const liveContext=live?await createAuthenticatedCliContext():undefined; const repository=liveContext?supabaseRepository(liveContext.client,liveContext.scope):memoryRepository();
  const contacts=await repository.list({includeArchived:args.includes('--include-archived')}); const result=createGovernedContactExport(contacts,{format,fields,includeArchived:args.includes('--include-archived')}); await writeFile(target,result.bytes);
  if(liveContext){const{error}=await liveContext.client.rpc('record_data_export_receipt',{target_workspace_id:liveContext.scope.workspaceId,target_actor_membership_id:liveContext.scope.membershipId,target_entity_type:'contacts',target_format:format,target_selection:{fields,includeArchived:args.includes('--include-archived')},target_selection_hash:result.selectionHash,target_row_count:result.rowCount,target_outcome:'succeeded',target_correlation_id:randomUUID(),target_created_at:new Date().toISOString()});if(error)throw new Error('Export created but its immutable receipt could not be recorded.');}
  output({ok:true,schemaVersion:'data-portability.v1',command,mode:live?'live-authenticated':'sample-process-only',format,output:target,rowCount:result.rowCount,selectionHash:result.selectionHash});
} else if (command === 'keys') {
  const operation=args[1]; const context=await createAuthenticatedCliContext(); if(context.scope.role!=='owner')throw new Error('Only a workspace owner can manage API keys.');
  if(operation==='list'){const{data,error}=await context.client.from('operational_api_keys').select('id,name,key_prefix,scopes,state,expires_at,created_at,last_used_at').eq('workspace_id',context.scope.workspaceId).order('created_at',{ascending:false});if(error)throw error;output({ok:true,schemaVersion:'data-portability.v1',command:'keys.list',keys:data});}
  else if(operation==='create'){const name=value('--name');const scopes=(value('--scopes')??'contacts.read,status.read').split(',') as OperationalApiScope[];if(!name)throw new Error('--name is required.');if(scopes.some((scope)=>!OPERATIONAL_API_SCOPES.includes(scope)))throw new Error('One or more scopes are invalid.');const pepper=process.env.OMNIX_API_KEY_PEPPER?.trim();if(!pepper)throw new Error('OMNIX_API_KEY_PEPPER is required.');const generated=createOperationalApiPlaintext();const verifier=operationalApiVerifier(generated.plaintext,pepper);const days=Math.min(Math.max(Number(value('--expires-days')??90),1),365);const{data,error}=await context.client.rpc('create_operational_api_key',{target_workspace_id:context.scope.workspaceId,target_name:name,target_prefix:generated.prefix,target_verifier:verifier,target_scopes:scopes,target_expires_at:new Date(Date.now()+days*86400000).toISOString(),target_actor_membership_id:context.scope.membershipId,target_created_at:new Date().toISOString()});if(error)throw error;output({ok:true,schemaVersion:'data-portability.v1',command:'keys.create',warning:'Copy this key now. It will never be shown again.',plaintext:generated.plaintext,key:{id:data.id,name:data.name,prefix:data.key_prefix,scopes:data.scopes,expiresAt:data.expires_at}});}
  else if(operation==='rotate'){const id=args[2];if(!id)throw new Error('Key id is required.');const pepper=process.env.OMNIX_API_KEY_PEPPER?.trim();if(!pepper)throw new Error('OMNIX_API_KEY_PEPPER is required.');const generated=createOperationalApiPlaintext();const days=Math.min(Math.max(Number(value('--expires-days')??90),1),365);const{data,error}=await context.client.rpc('rotate_operational_api_key',{target_key_id:id,target_new_prefix:generated.prefix,target_new_verifier:operationalApiVerifier(generated.plaintext,pepper),target_expires_at:new Date(Date.now()+days*86400000).toISOString(),target_actor_membership_id:context.scope.membershipId,target_rotated_at:new Date().toISOString()});if(error)throw error;output({ok:true,schemaVersion:'data-portability.v1',command:'keys.rotate',warning:'Copy this replacement key now. It will never be shown again.',plaintext:generated.plaintext,key:{id:data.id,prefix:data.key_prefix,rotatedFrom:data.rotated_from_key_id,expiresAt:data.expires_at}});}
  else if(operation==='revoke'){const id=args[2];if(!id)throw new Error('Key id is required.');const{data,error}=await context.client.rpc('revoke_operational_api_key',{target_key_id:id,target_actor_membership_id:context.scope.membershipId,target_revoked_at:new Date().toISOString()});if(error)throw error;output({ok:true,schemaVersion:'data-portability.v1',command:'keys.revoke',key:{id:data.id,prefix:data.key_prefix,state:data.state,revokedAt:data.revoked_at},correlationId:randomUUID()});}
  else throw new Error('Usage: npm run data -- keys list|create|rotate|revoke ...');
} else if(command==='webhooks'){
  const operation=args[1];const context=await createAuthenticatedCliContext();if(context.scope.role!=='owner')throw new Error('Only a workspace owner can manage webhooks.');
  if(operation==='list'){const{data,error}=await context.client.from('generic_webhook_endpoints').select('id,name,endpoint_key,auth_mode,enabled,created_at,updated_at,generic_webhook_receipts(accepted,status_code,received_at)').eq('workspace_id',context.scope.workspaceId).order('created_at',{ascending:false});if(error)throw error;output({ok:true,schemaVersion:'data-portability.v1',command:'webhooks.list',webhooks:data});}
  else if(operation==='create'){const name=value('--name'),mode=value('--mode')==='bearer'?'bearer':'hmac-sha256',pepper=process.env.OMNIX_WEBHOOK_SECRET_PEPPER?.trim();if(!name||!pepper)throw new Error('--name and OMNIX_WEBHOOK_SECRET_PEPPER are required.');const credential=createWebhookCredential();const{data,error}=await context.client.rpc('create_generic_webhook_endpoint',{target_workspace_id:context.scope.workspaceId,target_name:name,target_endpoint_key:credential.endpointKey,target_auth_mode:mode,target_verifier:webhookSecretVerifier(credential.secret,pepper),target_actor_membership_id:context.scope.membershipId,target_created_at:new Date().toISOString()});if(error)throw error;output({ok:true,schemaVersion:'data-portability.v1',command:'webhooks.create',warning:'Copy the secret now. It will never be shown again.',endpoint:`/api/v1/webhooks/${data.endpoint_key}`,secret:credential.secret,mode:data.auth_mode});}
  else if(operation==='rotate'){const id=args[2],pepper=process.env.OMNIX_WEBHOOK_SECRET_PEPPER?.trim();if(!id||!pepper)throw new Error('Endpoint id and OMNIX_WEBHOOK_SECRET_PEPPER are required.');const credential=createWebhookCredential();const overlapMinutes=Math.min(Math.max(Number(value('--overlap-minutes')??15),1),1440);const now=new Date();const{data,error}=await context.client.rpc('rotate_generic_webhook_secret',{target_endpoint_id:id,target_new_verifier:webhookSecretVerifier(credential.secret,pepper),target_overlap_until:new Date(now.getTime()+overlapMinutes*60000).toISOString(),target_actor_membership_id:context.scope.membershipId,target_rotated_at:now.toISOString()});if(error)throw error;output({ok:true,schemaVersion:'data-portability.v1',command:'webhooks.rotate',warning:'Copy the replacement secret now. It will never be shown again.',endpoint:`/api/v1/webhooks/${data.endpoint_key}`,secret:credential.secret,overlapMinutes});}
  else throw new Error('Usage: npm run data -- webhooks list|create|rotate ...');
} else {
  process.stderr.write('Usage: npm run data -- template|preview|export|keys|webhooks ...\n'); process.exitCode = 2;
}
