import { randomUUID } from 'node:crypto';
import type { Metadata } from 'next';
import Link from 'next/link';
import { CalendarCheck, CircleDollarSign, Clock3, ExternalLink, ShieldCheck } from 'lucide-react';
import { getRepository } from '@/lib/data';
import { createTransactionMilestoneAction, transitionTransactionMilestoneAction } from './actions';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Transactions & Deadlines' };

const day = (value: string) => new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(value));
const money = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(cents / 100);

export default async function TransactionsPage() {
  const context = await getRepository();
  const [transactions, milestones] = await Promise.all([
    context.transactionRepository.list(context.workspaceScope), context.operationalSignalRepository.listMilestones(context.workspaceScope, { limit: 500 }),
  ]);
  const open = milestones.filter((item) => item.state === 'open'); const now = Date.now();
  const overdue = open.filter((item) => Date.parse(item.dueAt) < now).length;
  return <div>
    <header className="mb-8 md:mb-10"><p className="eyebrow">Deal command center</p><h1 className="mt-2 max-w-4xl font-display text-[2.5rem] leading-[1.02] text-ink sm:text-5xl md:text-[3.6rem]">Every deadline. <span className="text-muted">Nothing inferred.</span></h1><p className="mt-4 max-w-2xl text-[16px] leading-relaxed text-muted">Track verified contract milestones, expected commission and closing dates. Omnix elevates deadlines into Approvals before work is created.</p></header>
    <section className="mb-6 grid overflow-hidden rounded-[var(--sk-card-radius)] border border-line bg-line sm:grid-cols-3">
      <article className="flex min-h-28 items-end justify-between bg-surface p-5"><div><strong className="font-display text-4xl text-ink">{transactions.filter((item) => item.status === 'pending' || item.status === 'under-contract').length}</strong><p className="mt-1 text-xs font-medium uppercase tracking-[0.1em] text-muted">Active deals</p></div><CircleDollarSign className="size-5 text-accent" aria-hidden /></article>
      <article className="flex min-h-28 items-end justify-between bg-surface p-5"><div><strong className="font-display text-4xl text-ink">{open.length}</strong><p className="mt-1 text-xs font-medium uppercase tracking-[0.1em] text-muted">Open deadlines</p></div><CalendarCheck className="size-5 text-accent" aria-hidden /></article>
      <article className="flex min-h-28 items-end justify-between bg-surface p-5"><div><strong className="font-display text-4xl text-ink">{overdue}</strong><p className="mt-1 text-xs font-medium uppercase tracking-[0.1em] text-muted">Overdue</p></div><Clock3 className="size-5 text-accent" aria-hidden /></article>
    </section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(20rem,0.7fr)]">
      <section className="grid gap-3" aria-label="Transaction deadlines">{milestones.length ? milestones.map((item) => <article id={`deadline-${item.id}`} key={item.id} className="rounded-[var(--sk-card-radius)] border border-line bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] ${item.state === 'open' ? Date.parse(item.dueAt) < now ? 'border-hot-border bg-hot-soft text-hot' : 'border-warm-border bg-warm-soft text-warm' : 'border-line bg-surface-2 text-muted'}`}>{item.state}</span><h2 className="mt-3 font-display text-2xl text-ink">{item.label}</h2><p className="mt-1 text-sm text-muted">{item.contactName} · {item.propertyAddress}</p></div><div className="text-right"><strong className="block text-sm text-ink">{day(item.dueAt)}</strong><span className="text-xs text-muted">{money(item.potentialValueCents)} potential GCI</span></div></div>{item.state === 'open' ? <div className="mt-5 flex flex-wrap gap-2 border-t border-line pt-4">{(['completed','waived','cancelled'] as const).map((state) => <form action={transitionTransactionMilestoneAction} key={state}><input type="hidden" name="milestoneId" value={item.id}/><input type="hidden" name="version" value={item.currentVersion}/><button name="state" value={state} className={state === 'completed' ? 'sk-button-primary' : 'sk-secondary-button'}>{state === 'completed' ? 'Mark complete' : state === 'waived' ? 'Mark waived' : 'Cancel'}</button></form>)}<Link href={`/contacts/${item.contactId}`} className="sk-secondary-button ml-auto">Open contact <ExternalLink className="size-4" aria-hidden/></Link></div> : null}</article>) : <article className="rounded-[var(--sk-card-radius)] border border-line bg-surface px-6 py-14 text-center"><CalendarCheck className="mx-auto size-8 text-accent"/><h2 className="mt-4 font-display text-2xl text-ink">No verified deadlines yet.</h2><p className="mt-2 text-sm text-muted">Add a deal with an expected close date or record a milestone here.</p></article>}</section>
      <form action={createTransactionMilestoneAction} className="h-fit rounded-[var(--sk-card-radius)] border border-line bg-surface p-5 xl:sticky xl:top-6"><p className="eyebrow">Verified milestone</p><h2 className="mt-2 font-display text-2xl text-ink">Add a deadline</h2><p className="mt-2 text-sm text-muted">Use the exact date from the contract or transaction file.</p><input type="hidden" name="idempotencyKey" value={randomUUID()}/><div className="mt-5 grid gap-4"><label className="text-sm font-medium text-ink">Transaction<select className="sk-input mt-1 w-full" name="transactionId" required defaultValue=""><option value="" disabled>Select a deal</option>{transactions.map((item) => <option value={item.id} key={item.id}>{item.contactName} · {item.propertyAddress}</option>)}</select></label><label className="text-sm font-medium text-ink">Type<select className="sk-input mt-1 w-full" name="kind" defaultValue="inspection"><option value="inspection">Inspection</option><option value="financing">Financing</option><option value="appraisal">Appraisal</option><option value="title">Title</option><option value="contingency">Contingency</option><option value="closing">Closing</option><option value="custom">Custom</option></select></label><label className="text-sm font-medium text-ink">Deadline name<input className="sk-input mt-1 w-full" name="label" maxLength={120} required placeholder="Inspection period ends"/></label><label className="text-sm font-medium text-ink">Due date<input className="sk-input mt-1 w-full" type="date" name="dueDate" required/></label><button className="sk-button-primary w-full justify-center" disabled={!transactions.length}>Save verified deadline</button></div><p className="mt-4 flex gap-2 text-xs leading-relaxed text-muted"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-nurture"/>Omnix may propose work from this date, but a person must approve the action.</p></form>
    </div>
  </div>;
}
